stages:
  - build
  - test

default:
  before_script:
    - docker info

build:
  stage: build
  image: docker:latest
  script:
    - docker -v
    - docker compose build

test:
  stage: test
  image: golang:latest
  script:
    - go test -v