stages:
  - build
  - test

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker -v
    - docker build -t my-app .

test:
  stage: test
  image: golang:latest
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
  script:
    - docker images
    - docker run -d --name my-app-test my-app
    - go test -v
  after_script:
    - docker stop my-app-test
    - docker rm my-app-test
