stages:
  - build
  - test

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker -v
    - docker compose up -d

test:
  stage: test
  image: golang:latest
  services:
    - docker:dind
  script:
    - docker-compose ps
    - go test ./tests -v
  after_script:
    - docker-compose down