image: docker:24.0.2

stages:
  - build
  - test

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

before_script:
  - docker info

build:
  stage: build
  script:
    - docker build -t myapp:latest .
    - docker images | grep myapp

test:
  stage: test
  image: golang:1.21
  script:
    - go test ./... -v
  only:
    - main