stages:
  - build
  - test

build:
  stage: build
  image: docker:27-rc-dind
  script:
    - docker --version
    - docker info
    - docker compose .

test:
  stage: test
  image: golang:latest
  script:
    - go test ./... -v
  only:
    - main
