stages:
  - build
  - test

services:
  - name: harbor.example.com/dockerhub-proxy-cache/library/docker:27-rc-dind
    alias: docker

build:
  stage: build
  image: docker
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
  script:
    - echo "Текущий рабочий каталог:"
    - pwd
    - echo "Содержимое каталога:"
    - ls -la
    - echo "Попытка запустить docker-compose:"
    - docker --version
    - docker compose up --build -d
  artifacts:
    paths:
      - docker-compose.yml

test:
  stage: test
  image: golang:latest
  script:
    - go test ./... -v
  only:
    - main
