stages:
  - build
  - test

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker -v
    - docker compose build

test:
  stage: test
  image: golang:latest
  services:
    - docker:dind
  script:
    - go test -v