image: docker:24.0.2

stages:
  - build
  - test

variables:
  DOCKER_HOST: "tcp://docker:2375"
  DOCKER_TLS_CERTDIR: ""

services:
  - docker:dind

before_script:
  - docker --version
  - go version || apk add --no-cache go

build:
  stage: build
  script:
    - docker build -t myapp:latest .
    - docker images | grep myapp

test:
  stage: test
  image: golang:1.21
  script:
    - go test ./... -v
  only:
    - main