stages:
  - build
  - test

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker -v
    - mkdir -p conf
    - echo "user nginx;" > conf/nginx.conf
    - docker compose up

test:
  stage: test
  image: golang:latest
  services:
    - docker:dind
  script:
    - go test ./tests -v