stages:
  - build
  - test

build:
  stage: build
  image: docker:latest
  script:
    - docker --version
    - docker compose build
  artifacts:
    paths:
      - docker-compose.yml

test:
  stage: test
  image: golang:latest
  script:
    - go test ./... -v
  only:
    - main
