stages:
  - build
  - test

build:
  stage: build
  image: docker:latest
  script:
    - docker -v
    - docker build -t order_service .
    - docker compose build

test:
  stage: test
  image: golang:latest
  script:
    - go test -v