stages:
  - build
  - test

build:
  stage: build
  image: docker:27-rc-cli
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375/
  script:
    - docker --version
    - docker compose up --build -d
  artifacts:
    paths:
      - docker-compose.yml

test:
  stage: test
  image: golang:latest
  script:
    - go test ./... -v
  only:
    - main
