stages:
  - build
  - test

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - ls
    - ls -l ./conf/nginx.conf
    - docker compose up -d
    - sleep 5
    - docker exec -i postgres_container psql -U root -d order_service -f /docker-entrypoint-initdb.d/init.sql

test:
  stage: test
  image: golang:latest
  services:
    - docker:dind 
  script:
    - go test -v